name: Apple-Clang Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_CONAN_CLASS: "ClapackConan"
  SINTEF_REFERENCE: "clapack*"
  CONAN_UPLOAD: "https://api.bintray.com/conan/sintef-ocean/conan"
  CONAN_PASSWORD_SINTEF: ${{ secrets.BINTRAY_API_KEY }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.BINTRAY_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-with-apple-clang:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [apple-clang]
        compiler_version: [11.0]
        build_type: [Debug, Release]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install conan requests
      - name: Configure Conan
        run: conan remote add sintef ${CONAN_UPLOAD} --insert 0
      - name: Conan create
        run: |
          conan create \
            -s build_type=${{ matrix.build_type }} \
            -s compiler=apple-clang \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.libcxx=libc++ \
            -b missing -b outdated . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 5 --force
      - name: Bintray info
        run: |
          python3 bintray.py ${SINTEF_CONAN_CLASS} \
            ${CONAN_LOGIN_USERNAME_SINTEF} ${CONAN_PASSWORD_SINTEF}
